# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Define statsd_file_statsd_service_dest
  set_fact:
    statsd_file_statsd_service_dest: "{{ __statsd_file_statsd_service_dest }}"
  when: statsd_file_statsd_service_dest is not defined

- name: Define statsd_file_statsd_service_mode
  set_fact:
    statsd_file_statsd_service_mode: "{{ __statsd_file_statsd_service_mode }}"
  when: statsd_file_statsd_service_mode is not defined

- name: Define statsd_file_statsd_service_src
  set_fact:
    statsd_file_statsd_service_src: "{{ __statsd_file_statsd_service_src }}"
  when: statsd_file_statsd_service_src is not defined

- name: Define statsd_file_statsd_service_config_dest
  set_fact:
    statsd_file_statsd_service_config_dest: "{{ __statsd_file_statsd_service_config_dest  }}"
  when: statsd_file_statsd_service_config_dest is not defined

- name: Define statsd_file_statsd_service_config_mode
  set_fact:
    statsd_file_statsd_service_config_mode: "{{ __statsd_file_statsd_service_config_mode  }}"
  when: statsd_file_statsd_service_config_mode is not defined

- name: Define statsd_file_statsd_service_config_src
  set_fact:
    statsd_file_statsd_service_config_src: "{{ __statsd_file_statsd_service_config_src  }}"
  when: statsd_file_statsd_service_config_src is not defined

- name: Install statsd service script into place
  become: yes
  template:
    dest: "{{ statsd_file_statsd_service_dest }}"
    group: "{{ statsd_file_statsd_service_group }}"
    mode: "{{ statsd_file_statsd_service_mode }}"
    owner: "{{ statsd_file_statsd_service_owner }}"
    src: "{{ statsd_file_statsd_service_src }}"
  register: statsd_file_statsd_service
  when: statsd_file_statsd_service_manage

- name: Create statsd service config directory
  become: yes
  file:
    group: "{{ statsd_file_statsd_service_config_group }}"
    owner: "{{ statsd_file_statsd_service_config_owner }}"
    path: "{{ statsd_file_statsd_service_dest }}.d"
    state: directory
  when: statsd_file_statsd_service_config_manage

- name: Install statsd service config into place
  become: yes
  template:
    dest: "{{ statsd_file_statsd_service_config_dest  }}"
    group: "{{ statsd_file_statsd_service_config_group  }}"
    mode: "{{ statsd_file_statsd_service_config_mode  }}"
    owner: "{{ statsd_file_statsd_service_config_owner  }}"
    src: "{{ statsd_file_statsd_service_config_src  }}"
  register: statsd_file_statsd_service_config
  when: statsd_file_statsd_service_config_manage

- name: Enable statsd service
  become: yes
  systemd:
    daemon_reload: "{{ statsd_service_statsd_daemon_reload }}"
    enabled: "{{ statsd_service_statsd_enabled }}"
    name: "{{ statsd_service_statsd_name }}"
    state: "{{ statsd_service_statsd_state }}"
  register: statsd_service_statsd
  when: statsd_service_statsd_manage
